// Package audit provides the append-only audit log for security-sensitive
// operations on the device.
//
// The on-disk file at /var/log/obacht/audit.log (line-delimited JSON) is the
// canonical record. A mirror table in SQLite (`audit_log_index`) exists for
// fast tailing through obachtctl/IPC; both share a monotonic `seq` value
// generated by the DB.
//
// Writes are serialized through a single mutex inside the Writer. Concurrent
// Append calls are safe but ordered; the hot path is a few microseconds plus
// one DB INSERT and one os.File Write/Sync.
//
// Phase S1 wires this writer into the IPC admin handlers and reconcile loop.
// Later phases (S2: deny inbound desired_state, S3: obachtctl mutators, S5:
// power-mode toggles) reuse the same Writer.
package audit

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"sync"
	"time"

	"github.com/obacht-dev/obacht-agent/internal/store"
)

// Result classifies the outcome of an audited operation.
type Result string

const (
	ResultOK     Result = "ok"
	ResultError  Result = "error"
	ResultDenied Result = "denied"
)

// Entry describes one audited event. Seq is assigned by Append.
type Entry struct {
	Seq          int64          `json:"seq"`
	TS           int64          `json:"ts"`             // unix seconds
	Op           string         `json:"op"`             // e.g. "instance.upsert"
	Actor        string         `json:"actor"`          // "obachtctl" | "reconciler" | "template:<id>" | "backend"
	Target       string         `json:"target,omitempty"`
	Result       Result         `json:"result"`
	Params       map[string]any `json:"params,omitempty"`        // never include secrets
	ParamsHash   string         `json:"params_hash"`
	ParamsSummary string        `json:"params_summary,omitempty"`
	ErrorMessage string         `json:"error,omitempty"`
}

// Writer appends audit entries to both the on-disk JSONL file and the SQLite
// index table. A nil Writer is safe to use: all methods become no-ops, which
// keeps callers ergonomic when audit is disabled in unit tests.
type Writer struct {
	st   *store.Store
	mu   sync.Mutex
	file *os.File
	path string
}

// New opens (or creates) the audit log file at path and returns a Writer.
// The directory is created with mode 0750. The file is opened append-only
// with mode 0640 so it can be tailed by members of the `adm` group without
// being mutated.
func New(st *store.Store, path string) (*Writer, error) {
	if st == nil {
		return nil, errors.New("audit: store is required")
	}
	if path == "" {
		return nil, errors.New("audit: path is required")
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return nil, fmt.Errorf("audit mkdir: %w", err)
	}
	f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o640)
	if err != nil {
		return nil, fmt.Errorf("audit open %s: %w", path, err)
	}
	return &Writer{st: st, file: f, path: path}, nil
}

// Close flushes and closes the underlying file. Safe on a nil Writer.
func (w *Writer) Close() error {
	if w == nil || w.file == nil {
		return nil
	}
	w.mu.Lock()
	defer w.mu.Unlock()
	err := w.file.Close()
	w.file = nil
	return err
}

// Append records one audit entry. The DB row is written first so that `seq`
// is monotonic; the JSONL line is then appended with that same seq. A failure
// to write the file is logged via the returned error but does not roll back
// the DB row — the table is the durable source of truth for tailing.
//
// Safe to call on a nil Writer (no-op, returns nil).
func (w *Writer) Append(ctx context.Context, e Entry) error {
	if w == nil {
		return nil
	}
	if e.TS == 0 {
		e.TS = time.Now().Unix()
	}
	if e.Result == "" {
		e.Result = ResultOK
	}
	if e.Op == "" {
		return errors.New("audit: op is required")
	}
	if e.Actor == "" {
		return errors.New("audit: actor is required")
	}
	if e.ParamsHash == "" {
		e.ParamsHash = HashParams(e.Params)
	}

	w.mu.Lock()
	defer w.mu.Unlock()

	seq, err := store.InsertAudit(ctx, w.st, store.AuditRow{
		TS:            e.TS,
		Op:            e.Op,
		Actor:         e.Actor,
		Target:        e.Target,
		Result:        string(e.Result),
		ParamsHash:    e.ParamsHash,
		ParamsSummary: e.ParamsSummary,
		ErrorMessage:  e.ErrorMessage,
	})
	if err != nil {
		return fmt.Errorf("audit db insert: %w", err)
	}
	e.Seq = seq

	if w.file != nil {
		buf, err := json.Marshal(e)
		if err != nil {
			return fmt.Errorf("audit marshal: %w", err)
		}
		buf = append(buf, '\n')
		if _, err := w.file.Write(buf); err != nil {
			return fmt.Errorf("audit write: %w", err)
		}
		// fsync is overkill per-entry on a Pi SD card; rely on OS flushing
		// and journaling fs. We do call Sync on Close.
	}
	return nil
}

// Tail returns the most recent n entries, newest first.
func (w *Writer) Tail(ctx context.Context, n int) ([]Entry, error) {
	if w == nil {
		return nil, nil
	}
	if n <= 0 {
		n = 50
	}
	rows, err := store.TailAudit(ctx, w.st, n)
	if err != nil {
		return nil, err
	}
	out := make([]Entry, 0, len(rows))
	for _, r := range rows {
		out = append(out, Entry{
			Seq:           r.Seq,
			TS:            r.TS,
			Op:            r.Op,
			Actor:         r.Actor,
			Target:        r.Target,
			Result:        Result(r.Result),
			ParamsHash:    r.ParamsHash,
			ParamsSummary: r.ParamsSummary,
			ErrorMessage:  r.ErrorMessage,
		})
	}
	return out, nil
}

// HashParams returns the SHA-256 hex digest of canonical-JSON-encoded params.
// Maps are emitted with sorted keys so the same logical params always yield
// the same hash, regardless of Go map iteration order.
func HashParams(params map[string]any) string {
	if len(params) == 0 {
		return "sha256:empty"
	}
	canon := canonicalize(params)
	buf, err := json.Marshal(canon)
	if err != nil {
		// Should never happen: canonicalize only emits json-marshalable types.
		return "sha256:error"
	}
	sum := sha256.Sum256(buf)
	return "sha256:" + hex.EncodeToString(sum[:])
}

// canonicalize converts a map[string]any tree into a structure with sorted
// string keys so that JSON encoding is deterministic.
func canonicalize(v any) any {
	switch t := v.(type) {
	case map[string]any:
		keys := make([]string, 0, len(t))
		for k := range t {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		ordered := make([]any, 0, len(keys)*2)
		for _, k := range keys {
			ordered = append(ordered, k, canonicalize(t[k]))
		}
		return ordered
	case []any:
		out := make([]any, len(t))
		for i, x := range t {
			out[i] = canonicalize(x)
		}
		return out
	default:
		return v
	}
}

// CopyFile is a small helper used by tests/smoketests that want to snapshot
// the on-disk log. Not used by production code.
func CopyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()
	_, err = io.Copy(out, in)
	return err
}
